public class GuestPassengerTriggerHandler {
    public static void beforeInsert(List <GuestPassenger__c>gstList){
        
        
        
        
    }
    public static void beforeUpdate(List <GuestPassenger__c>gstList,Map<Id,GuestPassenger__c>gstOldMap){
        
        
        
    }
    
    public void avoidMoreThanFiveGuestPassenger(List <GuestPassenger__c>gstList){
        
        
    }
}